# Questions 
### Q.1 Total no. of matches played in 2017
### Q.2 Total number of matches won ny Mumbai Indians
### Q.3 Find all the matches in 2017
### Q.4 Total no. mathes played at Wankhede Stadium
### Q.5 List Top 20 matches win by most runs
### Q.6 Top 10 matches won by most wickets
### Q.7 List all the matches in which 1st umpire was AY Dandekar
### Q.8 List all the matches in which Man of the match was CH Gayle
### Q.9 List all the matches in 2016 with date in which RCB had won the toss
### Q.10 List all the matches in 2016 with date in which RCB had won the match

## axis0 for row and axis1 for column by defaults it understands axis0

In [157]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import pandas as pd

In [61]:
df = pd.read_csv("data/matches.csv").head()   #To load file from the storage
#HEAD is used to show number of rows or lines of data,bydefault it shows 5 lines

In [162]:
df.rename({'city': 'City','date':"Date", 'team1':'Team1','team2': 'Team2','result': 'Result','player_of_match': "Man of the Match"},axis=1,inplace=True)
#To rename the column names and inplace=True to make changes in originaL data

In [164]:
df.head(2)

,id,season,City,Date,Team1,Team2,toss_winner,toss_decision,Result,dl_applied,winner,win_by_runs,win_by_wickets,Man of the Match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN

In [169]:
df.drop("umpire2",axis=1)     #to delete one column
df.head(2)

,id,season,City,Date,Team1,Team2,toss_winner,toss_decision,Result,dl_applied,winner,win_by_runs,win_by_wickets,Man of the Match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN

In [177]:
df.drop(["umpire2","umpire3"],axis=1).head(2)  #To delete more than one columns
df.head(2)

,id,season,City,Date,Team1,Team2,toss_winner,toss_decision,Result,dl_applied,winner,win_by_runs,win_by_wickets,Man of the Match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN

In [179]:
df.dropna(how='any')    #To delete whole row which contains one or 'Na'
df.head(2)

,id,season,City,Date,Team1,Team2,toss_winner,toss_decision,Result,dl_applied,winner,win_by_runs,win_by_wickets,Man of the Match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN

In [180]:
df.dropna(how='all')    #To delete whole row which contains complete row containing all the value named 'Na'
df.head(2)

,id,season,City,Date,Team1,Team2,toss_winner,toss_decision,Result,dl_applied,winner,win_by_runs,win_by_wickets,Man of the Match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN

In [181]:
df.dropna(axis=1,how='all')    #To delete whole row which contains complete row containing all the value named 'Na'
df.head(2)

,id,season,City,Date,Team1,Team2,toss_winner,toss_decision,Result,dl_applied,winner,win_by_runs,win_by_wickets,Man of the Match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN

In [183]:
df['Date'].head(10)

0    2017-04-05
1    2017-04-06
2    2017-04-07
3    2017-04-08
4    2017-04-08
5    2017-04-09
6    2017-04-09
7    2017-04-10
8    2017-04-11
9    2017-04-12
Name: Date, dtype: object

In [184]:
df.iloc[::2,::2].head()

,id,City,Team1,toss_winner,Result,winner,win_by_wickets,venue,umpire2
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,normal,Sunrisers Hyderabad,0,"Rajiv Gandhi International Stadium, Uppal",NJ Llong
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,normal,Kolkata Knight Riders,10,Saurashtra Cricket Association Stadium,CK Nandan
4,5,Bangalore,Royal Challengers Bangalore,Royal Challengers Bangalore,normal,Royal Challengers Bangalore,0,M Chinnaswamy Stadium,NaN
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,normal,Mumbai Indians,4,Wankhede Stadium,CK Nandan
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,normal,Delhi Daredevils,0,Maharashtra Cricket Association Stadium,S Ravi

In [185]:
df.loc[df['umpire1']=='AY Dandekar'].head()

,id,season,City,Date,Team1,Team2,toss_winner,toss_decision,Result,dl_applied,winner,win_by_runs,win_by_wickets,Man of the Match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
8,9,2017,Pune,2017-04-11,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Delhi Daredevils,97,0,SV Samson,Maharashtra Cricket Association Stadium,AY Dandekar,S Ravi,NaN
13,14,2017,Kolkata,2017-04-15,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Kolkata Knight Riders,17,0,RV Uthappa,Eden Gardens,AY Dandekar,NJ Llong,NaN
18,19,2017,Hyderabad,2017-04-17,Sunrisers Hyderabad,Kings XI Punjab,Kings XI Punjab,field,normal,0,Sunrisers Hyderabad,5,0,B Kumar,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,A Deshmukh,NaN
24,25,2017,Pune,2017-04-22,Sunrisers Hyderabad,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,6,MS Dhoni,Maharashtra Cricket Association Stadium,AY Dandekar,A Deshmukh,NaN

In [186]:
df.loc[df['umpire1']=='AY Dandekar'].head()

,id,season,City,Date,Team1,Team2,toss_winner,toss_decision,Result,dl_applied,winner,win_by_runs,win_by_wickets,Man of the Match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
8,9,2017,Pune,2017-04-11,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Delhi Daredevils,97,0,SV Samson,Maharashtra Cricket Association Stadium,AY Dandekar,S Ravi,NaN
13,14,2017,Kolkata,2017-04-15,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Kolkata Knight Riders,17,0,RV Uthappa,Eden Gardens,AY Dandekar,NJ Llong,NaN
18,19,2017,Hyderabad,2017-04-17,Sunrisers Hyderabad,Kings XI Punjab,Kings XI Punjab,field,normal,0,Sunrisers Hyderabad,5,0,B Kumar,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,A Deshmukh,NaN
24,25,2017,Pune,2017-04-22,Sunrisers Hyderabad,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,6,MS Dhoni,Maharashtra Cricket Association Stadium,AY Dandekar,A Deshmukh,NaN

In [187]:
df.loc[df['umpire1']=='AY Dandekar'][10::2].head()

,id,season,City,Date,Team1,Team2,toss_winner,toss_decision,Result,dl_applied,winner,win_by_runs,win_by_wickets,Man of the Match,venue,umpire1,umpire2,umpire3
604,605,2016,Pune,2016-05-01,Rising Pune Supergiants,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,8,RG Sharma,Maharashtra Cricket Association Stadium,AY Dandekar,RJ Tucker,NaN
619,620,2016,Bangalore,2016-05-14,Royal Challengers Bangalore,Gujarat Lions,Gujarat Lions,field,normal,0,Royal Challengers Bangalore,144,0,AB de Villiers,M Chinnaswamy Stadium,AY Dandekar,VK Sharma,NaN

In [196]:
df.loc[df['City']=='Kolkata',['City','toss_decision','toss_winner']].head()

       City toss_decision                  toss_winner
10  Kolkata         field        Kolkata Knight Riders
13  Kolkata         field          Sunrisers Hyderabad
22  Kolkata         field                Gujarat Lions
26  Kolkata         field  Royal Challengers Bangalore
30  Kolkata         field        Kolkata Knight Riders

In [197]:
x = df.loc[df['Man of the Match'] =='CH Gayle',['Man of the Match','Team1']]

In [119]:
len(x)

20

In [198]:
df.loc[(df['winner']== 'Royal Challengers Bangalore') & (df['season']==2016)]

,id,season,City,Date,Team1,Team2,toss_winner,toss_decision,Result,dl_applied,winner,win_by_runs,win_by_wickets,Man of the Match,venue,umpire1,umpire2,umpire3
579,580,2016,Bangalore,2016-04-12,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Royal Challengers Bangalore,45,0,AB de Villiers,M Chinnaswamy Stadium,HDPK Dharmasena,VK Sharma,NaN
591,592,2016,Pune,2016-04-22,Royal Challengers Bangalore,Rising Pune Supergiants,Rising Pune Supergiants,field,normal,0,Royal Challengers Bangalore,13,0,AB de Villiers,Maharashtra Cricket Association Stadium,CB Gaffaney,VK Sharma,NaN
610,611,2016,Bangalore,2016-05-07,Rising Pune Supergiants,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,7,V Kohli,M Chinnaswamy Stadium,CB Gaffaney,BNJ Oxenford,NaN
614,615,2016,Chandigarh,2016-05-09,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,normal,0,Royal Challengers Bangalore,1,0,SR Watson,"Punjab Cricket Association IS Bindra Stadium, ...",AK Chaudhary,HDPK Dharmasena,NaN
619,620,2016,Bangalore,2016-05-14,Royal Challengers Bangalore,Gujarat Lions,Gujarat Lions,field,normal,0,Royal Challengers Bangalore,144,0,AB de Villiers,M Chinnaswamy Stadium,AY Dandekar,VK Sharma,NaN
623,624,2016,Kolkata,2016-05-16,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,9,V Kohli,Eden Gardens,CB Gaffaney,A Nand Kishore,NaN
625,626,2016,Bangalore,2016-05-18,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,normal,1,Royal Challengers Bangalore,82,0,V Kohli,M Chinnaswamy Stadium,KN Ananthapadmanabhan,M Erasmus,NaN
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN

In [199]:
df.loc[(df['winner']== 'Royal Challengers Bangalore') & (df['season']==2016)  & (df['toss_winner'] == 'Royal Challengers Bangalore')]

,id,season,City,Date,Team1,Team2,toss_winner,toss_decision,Result,dl_applied,winner,win_by_runs,win_by_wickets,Man of the Match,venue,umpire1,umpire2,umpire3
610,611,2016,Bangalore,2016-05-07,Rising Pune Supergiants,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,7,V Kohli,M Chinnaswamy Stadium,CB Gaffaney,BNJ Oxenford,NaN
623,624,2016,Kolkata,2016-05-16,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,9,V Kohli,Eden Gardens,CB Gaffaney,A Nand Kishore,NaN
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN

In [201]:
df.loc[(df['winner']== 'Royal Challengers Bangalore') & (df['season']==2016)  & (df['toss_winner'] == 'Royal Challengers Bangalore'),["Team1","Team2","Match of the Match"]]

                       Team1                        Team2  Match of the Match
610  Rising Pune Supergiants  Royal Challengers Bangalore                 NaN
623    Kolkata Knight Riders  Royal Challengers Bangalore                 NaN
631         Delhi Daredevils  Royal Challengers Bangalore                 NaN
632            Gujarat Lions  Royal Challengers Bangalore                 NaN

In [203]:
df.sort_values(by="win_by_runs",ascending=False).head()

,id,season,City,Date,Team1,Team2,toss_winner,toss_decision,Result,dl_applied,winner,win_by_runs,win_by_wickets,Man of the Match,venue,umpire1,umpire2,umpire3
43,44,2017,Delhi,2017-05-06,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Mumbai Indians,146,0,LMP Simmons,Feroz Shah Kotla,Nitin Menon,CK Nandan,NaN
619,620,2016,Bangalore,2016-05-14,Royal Challengers Bangalore,Gujarat Lions,Gujarat Lions,field,normal,0,Royal Challengers Bangalore,144,0,AB de Villiers,M Chinnaswamy Stadium,AY Dandekar,VK Sharma,NaN
59,60,2008,Bangalore,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,NaN
556,557,2015,Bangalore,2015-05-06,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,normal,0,Royal Challengers Bangalore,138,0,CH Gayle,M Chinnaswamy Stadium,RK Illingworth,VA Kulkarni,NaN
410,411,2013,Bangalore,2013-04-23,Royal Challengers Bangalore,Pune Warriors,Pune Warriors,field,normal,0,Royal Challengers Bangalore,130,0,CH Gayle,M Chinnaswamy Stadium,Aleem Dar,C Shamshuddin,NaN

In [204]:
y = df.loc[df["venue"]=="Wankhede Stadium"]
len(y)

66